### PR TITLE
[BPKR-130] New API to force Bottom Sheet layout refresh

### PR DESCRIPTION
**Pull request by fedetrim**
This PR adds a new API that allows for refreshing bottom sheet layout, for example to resize it according to content constraints changes:

Screen-Recording-2020-03-17-at-18 46 32

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/master/CONTRIBUTING.md)

Remember to include the following changes:
+ [x] `UNRELEASED.md`
+ [] `README.md`
+ [] Tests
+ [] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/master/Example/Backpack%20Screenshot/Screenshots.swift)
+ [] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Backpack.h)
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by imchristian** [comment]
There's no way to rely on autolayout to perform the resizing based on the intrinsic content size? 🤔 

Side note: please rebase with master to resolve the merge conflict 👍

**Comment by fedetrim** [comment]
> @imchristian: There's no way to rely on autolayout to perform the resizing based on the intrinsic content size instead of proactively call the updateLayout func? 🤔
>
>Side note: please rebase with master to resolve the merge conflict 👍

@imchristian I tried that but unfortunately it didn't work because apparently `FloatingPanel` creates constraints on their own based on the intrinsic content size that the view had when first loading (similarly to how table view works), and then I found that `FloatingPanel` has this `updateLayout()` API so apparently it is expected to be used this way.

Regarding merge conflicts, can I just solve them using GitHub and then just merge with "Squash and merge" to get a single commit on `master`?

**Comment by fedetrim** [comment]
@imchristian Just solved conflicts. Let me know if my previous comment makes sense :)

**Comment by imchristian** [comment]
LGTM, feel free to squash and merge it 👍

**Pull request merged**
