### PR TITLE
Add Persistent and Modal Presentation Style

### PR DESCRIPTION
**Pull request by paulomendes**
## Add Persistent and Modal Presentation Style

This PR has the objective to introduce a new style of presentation to BottomSheet. Now we are capable to present it modally or persistently.

# Persistent Bottom Sheet

It can be initialized by using

```Swift
let bottomSheet = BPKBottomSheet(contentViewController: viewController, 
 scrollViewToTrack: viewController.tableView, 
 bottomSectionViewController: nil, 
 presentationStyle: .persistent)
```

To use the `.persistent` presentation style we need to ensure to use the method `addPanel` instead of `present`.

This will allow the following behavior. 

ezgif-6-7f75e33ed95b

# What is New

- New parameter in the initialization called `presentationStyle` which is an enum
```Swift
public enum PresentationStyle {
        case modal
        case persistent
    }
```
- New layout definition: `ModalBottomSheetLayout` and `PersistentBottomSheetLayout`
- New `addPanel(toParent parent: UIViewController)` method, that will add a BottomSheet and make it persistent and allow you to interact with the parent view controller
- New `removePanel(animated: Bool)` in case you added a BottomSheet persistently but needs to hide it for some loading interaction or something else.
- New `public func move(to position: BPKFloatingPanelPosition)` that will allow you to programmatically change the position of the BottomSheet.

+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/master/CONTRIBUTING.md)

Remember to include the following changes:
+ [x] `UNRELEASED.md`
+ [x] `README.md`
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/master/Example/Backpack%20Screenshot/Screenshots.swift)
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Backpack.h)
+ [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Review by k0nserv — APPROVED** [review]

**Review by fedetrim — APPROVED** [review]
This LGTM from a code point of view. Would it be too much to ask you to create a PR in the main app repo linking to this branch of Backpack? So that it generates a QR code that I can use to test current features before we merge this

**Comment by k0nserv** [comment]
We can do that with an alpha release from this branch if you want @fedetrim

**Comment by fedetrim** [comment]
@k0nserv sounds good!

**Comment by k0nserv** [comment]
@fedetrim I published an alpha as 40.1.0-alpha.0

**Pull request merged**
