### PR TITLE
[No Jira] Migrate button, card, calendar and flare to new story format

### PR DESCRIPTION
**Pull request by shaundon**
I haven't done any of the other components as it looks like they aren't migrated to the navigation format anyway.

### CODE REVIEW

**Review by k0nserv — APPROVED** [review]
Very neat 🎉

**Comment by georgegillams** [comment]
Have you tested the screenshotting code still works?
I'm happy to test it for you if not...

**Comment by shaundon** [comment]
> Have you tested the screenshotting code still works? I'm happy to test it for you if not...

I haven't, how can I do that?

**Comment by georgegillams** [comment]
> > Have you tested the screenshotting code still works? I'm happy to test it for you if not...
> 
> I haven't, how can I do that?

With the simulator app closed run `rake take_screenshots`.
It will build the project, take all the screenshots. Make sure it exits ok and the screenshots are updated.

It takes about 20 mins to run, so that's normal.

**Comment by shaundon** [comment]
Thanks, just ran it and it did fail, I think it's probably because I renamed a couple of the links. I'll fix it in the morning

**Comment by shaundon** [comment]
@georgegillams I changed the names back and the screenshots are all good now. Will merge.

**Pull request merged**
