### PR TITLE
[BPK-4321] Upgrade floating-panel dependency

### PR DESCRIPTION
**Pull request by k0nserv**
<details>
<summary>After(2.1.0)</summary>

https://user-images.githubusercontent.com/1333960/102518085-c0d75700-4088-11eb-9128-c9aa544bcd4b.mov

</details>

<details>
<summary>Before(1.6.6)</summary>

https://user-images.githubusercontent.com/1333960/102517113-8d47fd00-4087-11eb-986a-55c2eafa0e5f.mov

</details>

There's some wonkiness with the intrinsic content size version still. I'm unsure if it's even possible to prevent the scrolling entirely and there's a bit of weird text trunacting going on with the static case

+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/master/CONTRIBUTING.md)

Remember to include the following changes:
+ [ ] `UNRELEASED.md`
+ [x] `README.md`
+ [x] Tests
+ [x] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/master/Example/Backpack%20Screenshot/Screenshots.swift)
+ [x] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Backpack.h)
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md)_

### CODE REVIEW

**Comment by fedetrim** [comment]
We are using the "non-scrollable" style a lot in Trips, and looks like with the new changes, this style is having issues with the safe area layout guide and the intrinsic size of the content.

Do you think it's related to https://github.com/Skyscanner/backpack-ios/pull/833/files#diff-d16f28063a7492d7af08a8c3e66527bd269c890722eb29c968bee41aea7f38efR203-R207 ...?

Maybe we should use `safeArea` instead of `superview`/

**Comment by k0nserv** [comment]
> We are using the "non-scrollable" style a lot in Trips, and looks like with the new changes, this style is having issues with the safe area layout guide and the intrinsic size of the content.
> 
> 
> 
> Do you think it's related to https://github.com/Skyscanner/backpack-ios/pull/833/files#diff-d16f28063a7492d7af08a8c3e66527bd269c890722eb29c968bee41aea7f38efR203-R207 ...?
> 
> 
> 
> Maybe we should use `safeArea` instead of `superview`?

I tried both `safeArea` and `superView`. I believe I settled on `superView` because it matched the current behaviour. I don't recall if `safeArea` exhibit the same layout issues, will test this tomorrow and get back to you

**Comment by georgegillams** [comment]
As far as I can tell this is working well, apart from this strange behaviour:


Is this the same issue you're referring to @fedetrim?

**Comment by fedetrim** [comment]
@georgegillams No, I'm referring to second 18 of the first video fo the description, when you tap on "Bottom Sheet with a non-scrollable content". Notice how the sheet doesn't have the right size to fit the content, and seems to be ignoring safe area as well. Also the size changes a few times in a strange way as you scroll

**Comment by k0nserv** [comment]
I don't think there's a way to lock the scroll in place with this new API anymore, at least I haven't been able to spot anything like it

**Comment by fedetrim** [comment]
@k0nserv 
I think we don't need to lock the scroll in place though as long as we can make it work without any UI glitches

**Comment by k0nserv** [comment]
Update it to use `.safeArea` instead, this doesn't have the visual issues of `.superView` but does mean the height will differ from the previous version.

**Comment by k0nserv** [comment]
https://github.com/Skyscanner/backpack-ios/pull/833/commits/01422987548d67736d5951799ac462ff4916dc75 fixes the issues with dragging when using the intrinsic size mode(by disabling it entirely). 

I think  now this should be good to merge

**Comment by georgegillams** [comment]
> [0142298](https://github.com/Skyscanner/backpack-ios/commit/01422987548d67736d5951799ac462ff4916dc75) fixes the issues with dragging when using the intrinsic size mode(by disabling it entirely).
> 
> I think now this should be good to merge.
> 
> This does mean you cannot swipe to dimiss non scrolalble panels anymore, I'm inclined to say we should keep the grabbable behaviour 🤔

I feel like swiping to dismiss is going to be the most expected behaviour from users 🤔

**Comment by k0nserv** [comment]
I agree 👍🏼 Let me remove that last part hten

**Comment by georgegillams** [comment]
This is still a little funky 🤔

**Comment by k0nserv** [comment]
How should that work in your opinion?

**Comment by fedetrim** [comment]
> This is still a little funky 🤔
> 

Yes, there's definitely an issue when calculating the size of the content. I think for scrolling it doesn't consider safe area but when animation ends, safe area is suddenly added and the size jumps to the correct value making it look like a UI glitch.
TBH I don't think this is an acceptable UX/UI, we should test integrating this branch into the main Skyscanner app and see how it looks on real features

**Comment by k0nserv** [comment]
Yeah, I'm going to checkout the examples in the main repo but I think that's intended behaviour

**Comment by k0nserv** [comment]
I've found and fixed the issues. The constraints for the views inside the bottom sheet should not reference the safearea, they should reference the superview.

**Review by georgegillams — APPROVED** [review]
It's beautiful!

**Comment by fedetrim** [comment]
@k0nserv 
>The constraints for the views inside the bottom sheet should not reference the safearea, they should reference the superview.

I think that's a workaround not ideal because if we wanted to reuse a view controller for presenting it in two different styles (maybe as a native modal, and also as a bottom sheet), then native modal would need constraints referencing safearea, but bottom sheet would need superview. So it's inconsistent.

However it might be an acceptable tradeoff in order to be able to update this framework to the latest version. Before merging and releasing this, it would be nice to have a branch in the main Skyscanner app repo using this branch of Backpack, so that we can make sure that all bottom sheets look and behave correctly and update the code if needed. Then we can release this, and then update the app repo branch to use the Backpack release version

**Comment by k0nserv** [comment]
Yeah I agree we need to see what the impact is on the live app, however this seems like a better outcome than the janky behaviour we'd otherwise get

**Comment by k0nserv** [comment]
I've done more investigating with the samples from FloatingPanel, as we've noticed there are two options:

+ Live with the janky behaviour on devices with a bottom safe area(it doesn't happen on i.e. an iPhone 8)
+ Fixed it by constraining to `superView.bottom` instead of `safeArea.bottom`. 

In either case this is a documentation issue not something we can fix in Backpack. It depends on how you wire up your views.

**Comment by k0nserv** [comment]
Closing for now

**Pull request closed without merging**
