### PR TITLE
Switch to Xcode 10

### PR DESCRIPTION
**Pull request by k0nserv**

### CODE REVIEW

**Comment by shaundon** [comment]
Runs fine on my machine - only thing is this warning - is this on my end or is it something we've missed?

screen shot 2018-10-16 at 11 28 48

**Comment by k0nserv** [comment]
> One question - why have the snapshot images changed? They look exactly the same to me

Tiny rendering difference between iOS 11 and iOS 12.

**Comment by k0nserv** [comment]
> Runs fine on my machine - only thing is this warning - is this on my end or is it something we've missed?

Let me look at

**Comment by k0nserv** [comment]
I don't get that warning locally

**Comment by shaundon** [comment]
Ok, thanks for checking. Let's just assume it's my setup.

**Pull request merged**
